# Workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll to GitHub Pages

# Trigger the workflow on pushes to the default branch and manual runs
on:
  push:
    branches:
      - master
  workflow_dispatch:

# Define permissions for the GITHUB_TOKEN
permissions:
  contents: read
  pages: write
  id-token: write

# Configure concurrency settings for deployments
concurrency:
  group: "pages"
  cancel-in-progress: false

# Define the jobs for building and deploying
jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Build Jekyll Site
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v2

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
